---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ivdoctr

<!-- badges: start -->
<!-- badges: end -->

Instrumental variables are a useful tool in causal inference. In order to be valid, researchers impose both formal beliefs (instrumental relevance and the exclusion restriction) and informal beliefs (e.g., correlation between endogenous treatment and the error term). The goal of `ivdoctr` is to formalize those beliefs and quantifies how sensitive a researcher's instrumental variables are to measurement error and instrument endogeneity. Using data and researcher's beliefs on measurement error and instrument endogeneity, this package generates the space of consistent beliefs across measurement error, instrument endogeneity, and instrumental relevance for IV regressions. 

## Installation

You can install the released version of ivdoctr from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ivdoctr")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("fditraglia/ivdoctr")
```

See vignettes for usage examples.
